# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_type', models.CharField(choices=[('A', 'Article'), ('P', 'Patent')], max_length=1)),
                ('pub_content', models.CharField(max_length=2000)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
