# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 12:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_publication_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.CompanyModel'),
        ),
    ]
