# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-15 12:19
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reqsubscriptionplan_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymodel',
            name='is_req_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='is_req_sub_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='req_sub_begin_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='companymodel',
            name='req_sub_end_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
