# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-18 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161118_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionplan',
            name='sub_type',
            field=models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('S', 'Super Premium')], max_length=1, unique=True),
        ),
    ]
