# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-19 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20161118_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpremiumfield',
            name='no_of_emp',
            field=models.PositiveIntegerField(blank=True, default=None),
        ),
    ]
