# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-28 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20161119_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymodel',
            name='company_email',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
