# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-30 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161128_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsLetterSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
